version: '3'

services:

  api:
    image: 'docker-spring-boot:latest'
    hostname: app
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    container_name: 'app'
    ports:
      - '8080:8080'